### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by MoonlightSV** [pabushabi/super-duper-site#1]
Позволяет выставить в желаемой зарплате большее значение слева. Например 12000 - 10000.
В дате рождения позволяет выставлять год больше текущего.
После выхода из профиля и попытки повторного входа ограничения на пароль, которые были пройдены при регистрации не воспринимают пароль и выдают ошибку.

**Comment by pabushabi** [comment]
Пункт №3 исправлен в коммите #9c20248
